### ISSUE TITLE
.

### ISSUE THREAD

**Issue by something-0001** [xHERMIS/ID-to-TOKEN#1]
Your luck in generating tokens is still quite shit, even with this revelation.

While the first part is indeed a base64 encode of your Discord ID, the rest of the token dissolves into a mess of cryptographic or unix-timestamp based things, which naturally you can't really decode on your own.

Not sure why would anyone use this tool, but, the sentiment is there I suppose. Just don't waste your boot power.

**Comment by xHERMIS** [comment]
### > Your luck in generating tokens is still quite shit, even with this revelation.
What should I do then ? Notice that this repository is for educational purpose only

### > While the first part is indeed a base64 encode of your Discord ID, the rest of the token dissolves into a mess of cryptographic or unix-timestamp based things, which naturally you can't really decode on your own.
No comment

> ### Not sure why would anyone use this tool, but, the sentiment is there I suppose. Just don't waste your boot power.
I am just trying to make anything in my spare time
