### ISSUE TITLE
10 stars!!

### ISSUE THREAD

**Issue by TheRealReed** [xHERMIS/ID-to-TOKEN#2]
i was your 10th star! Threads now 😈

**Comment by xHERMIS** [comment]
I will do it soon

**Comment by TheRealReed** [comment]
base64 link to the code: 
data:text/txt;base64,aW1wb3J0IG9zDQppbXBvcnQgYmFzZTY0DQppbXBvcnQgdGltZQ0KaW1wb3J0IHJhbmRvbQ0KaW1wb3J0IHN0cmluZw0KaW1wb3J0IHJlcXVlc3RzDQppbXBvcnQgdGhyZWFkaW5nDQpmcm9tIGNvbG9yYW1hIGltcG9ydCBGb3JlLCBpbml0LCBTdHlsZQ0KDQpkZWYgcHJpbnRfY29sb3JlZCh0ZXh0LCBjb2xvcl9jb2RlKToNCiAgICBwcmludChmIlwwMzNbe2NvbG9yX2NvZGV9bXt0ZXh0fVwwMzNbMG0iKQ0KDQojIENoZWNrIGFuZCBpbnN0YWxsIHJlcXVpcmVkIGxpYnJhcmllcw0KdHJ5Og0KICAgIGltcG9ydCByZXF1ZXN0cw0KZXhjZXB0IEltcG9ydEVycm9yOg0KICAgIHByaW50X2NvbG9yZWQoIkluc3RhbGxpbmcgcmVxdWVzdHMuLi4iLCAiMzEiKQ0KICAgIGltcG9ydCBzdWJwcm9jZXNzDQogICAgc3VicHJvY2Vzcy5jYWxsKFsicGlwIiwgImluc3RhbGwiLCAicmVxdWVzdHMiXSkNCiAgICBwcmludF9jb2xvcmVkKCJSZXF1ZXN0cyBpbnN0YWxsZWQhIiwgIjMyIikNCg0KdHJ5Og0KDQogICAgZnJvbSBjb2xvcmFtYSBpbXBvcnQgRm9yZSwgaW5pdCwgU3R5bGUNCmV4Y2VwdCBJbXBvcnRFcnJvcjoNCiAgICBwcmludF9jb2xvcmVkKCJJbnN0YWxsaW5nIGNvbG9yYW1hLi4uIiwgIjMxIikNCiAgICBpbXBvcnQgc3VicHJvY2Vzcw0KICAgIHN1YnByb2Nlc3MuY2FsbChbInBpcCIsICJpbnN0YWxsIiwgImNvbG9yYW1hIl0pDQogICAgcHJpbnRfY29sb3JlZCgiQ29sb3JhbWEgaW5zdGFsbGVkISIsICIzMiIpDQoNCmRlZiBjbGVhcl9jb25zb2xlKCk6DQogICAgb3Muc3lzdGVtKCJjbHMiKQ0KDQpkZWYgZW5jb2RlX2Jhc2U2NChpbnB1dF9zdHIpOg0KICAgIHJldHVybiBiYXNlNjQudXJsc2FmZV9iNjRlbmNvZGUoaW5wdXRfc3RyLmVuY29kZSgpKS5kZWNvZGUoKS5yc3RyaXAoIj0iKQ0KDQpkZWYgZ2VuZXJhdGVfcmFuZG9tX3N0cmluZyhrKToNCiAgICBjaGFyYWN0ZXJzID0gc3RyaW5nLmFzY2lpX2xldHRlcnMgKyBzdHJpbmcuZGlnaXRzICsgIi1fIg0KICAgIHJldHVybiAnJy5qb2luKHJhbmRvbS5jaG9pY2UoY2hhcmFjdGVycykgZm9yIF8gaW4gcmFuZ2UoaykpDQoNCmRlZiBnZXRfdG9rZW4odXNlcl9pZCk6DQogICAgdG9rZW4gPSBmIntlbmNvZGVfYmFzZTY0KHVzZXJfaWQpfS57Z2VuZXJhdGVfcmFuZG9tX3N0cmluZyg2KX0ue2dlbmVyYXRlX3JhbmRvbV9zdHJpbmcoMzgpfSINCiAgICByZXR1cm4gdG9rZW4NCg0KZGVmIGNoZWNrX3Byb3h5KHByb3h5KToNCiAgICB0cnk6DQogICAgICAgIHJlcXVlc3RzLmdldCgnaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbScsIHByb3hpZXM9eydodHRwJzogcHJveHksICdodHRwcyc6IHByb3h5fSwgdGltZW91dD01KQ0KICAgICAgICByZXR1cm4gVHJ1ZQ0KICAgIGV4Y2VwdCByZXF1ZXN0cy5SZXF1ZXN0RXhjZXB0aW9uOg0KICAgICAgICByZXR1cm4gRmFsc2UNCg0KZGVmIGNoZWNrX3Rva2VuX3ZhbGlkaXR5KHRva2VuLCBwcm94eSk6DQogICAgaGVhZGVycyA9IHsNCiAgICAgICAgJ0F1dGhvcml6YXRpb24nOiB0b2tlbiwNCiAgICB9DQogICAgdHJ5Og0KICAgICAgICBpZiBwcm94eToNCiAgICAgICAgICAgIGlmIGNoZWNrX3Byb3h5KHByb3h5KToNCiAgICAgICAgICAgICAgICBsb2dpbiA9IHJlcXVlc3RzLmdldCgnaHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvdjkvdXNlcnMvQG1lJywgaGVhZGVycz1oZWFkZXJzLCBwcm94aWVzPXsnaHR0cCc6IHByb3h5LCAnaHR0cHMnOiBwcm94eX0pDQogICAgICAgICAgICBlbHNlOg0KICAgICAgICAgICAgICAgIHByaW50KGYie0ZvcmUuUkVEfVstXSBQcm94eSBub3Qgd29ya2luZywgc2tpcHBpbmcgdG9rZW4gY2hlY2sue0ZvcmUuUkVTRVR9IikNCiAgICAgICAgICAgICAgICByZXR1cm4NCiAgICAgICAgZWxzZToNCiAgICAgICAgICAgIGxvZ2luID0gcmVxdWVzdHMuZ2V0KCdodHRwczovL2Rpc2NvcmRhcHAuY29tL2FwaS92OS91c2Vycy9AbWUnLCBoZWFkZXJzPWhlYWRlcnMpDQoNCiAgICAgICAgaWYgbG9naW4uc3RhdHVzX2NvZGUgPT0gMjAwOg0KICAgICAgICAgICAgcHJpbnQoZiJ7Rm9yZS5HUkVFTn1bK10gVkFMSUQge3Rva2VufXtGb3JlLlJFU0VUfSIpDQogICAgICAgICAgICB3aXRoIG9wZW4oJ2hpdC50eHQnLCAiYSsiKSBhcyBmOg0KICAgICAgICAgICAgICAgIGYud3JpdGUoZid7dG9rZW59XG4nKQ0KICAgICAgICBlbHNlOg0KICAgICAgICAgICAgcHJpbnQoZiJ7Rm9yZS5SRUR9Wy1dIElOVkFMSUQge3Rva2VufXtGb3JlLlJFU0VUfSIpDQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOg0KICAgICAgICBwcmludChmIntGb3JlLlJFRH1bLV0gRVJST1IgT0NDVVJSRUQge3Rva2VufSIpDQogICAgICAgIHByaW50KGYiRXJyb3IgZGV0YWlsczoge2V9IikNCg0KZGVmIHJlYWRfcHJveGllc19mcm9tX2ZpbGUoZmlsZV9wYXRoKToNCiAgICB3aXRoIG9wZW4oZmlsZV9wYXRoLCAncicpIGFzIGZpbGU6DQogICAgICAgIHByb3hpZXMgPSBbbGluZS5zdHJpcCgpIGZvciBsaW5lIGluIGZpbGUgaWYgbGluZS5zdHJpcCgpXQ0KICAgIHJldHVybiBwcm94aWVzDQoNCmRlZiBwcmludF9iYW5uZXIoKToNCiAgICBiYW5uZXIgPSAoRm9yZS5NQUdFTlRBICsgIiIiDQrilojilojigIEgIOKWiOKWiOKAgeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKAgeKWiOKWiOKWiOKWiOKWiOKWiOKAgSDilojilojilojigIEgICDilojilojilojigIHilojilojigIHilojilojilojilojilojilojilojigIENCuKWiOKWiOKAgSAg4paI4paI4oCB4paI4paI4oCB4oCB4oCB4oCB4oCB4oCB4paI4paI4oCB4oCB4oCB4paI4paI4oCB4paI4paI4paI4paI4oCBIOKWiOKWiOKWiOKWiOKAgeKWiOKWiOKAgeKWiOKWiOKAgeKAgeKAgeKAgeKAgeKAgQ0K4paI4paI4paI4paI4paI4paI4paI4oCB4paI4paI4paI4paI4paI4oCBICDilojilojilojilojilojilojigIHigIHilojilojigIHilojilojilojilojigIHilojilojigIHilojilojigIHilojilojilojilojilojilojilojigIENCuKWiOKWiOKAgeKAgeKAgeKWiOKWiOKAgeKWiOKWiOKAgeKAgeKAgeKAgSAg4paI4paI4oCB4oCB4oCB4paI4paI4oCB4paI4paI4oCB4oCB4paI4paI4oCB4oCB4paI4paI4oCB4paI4paI4oCB4oCB4oCB4oCB4oCB4oCB4paI4paI4oCBDQrilojilojigIEgIOKWiOKWiOKAgeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKAgeKWiOKWiOKAgSAg4paI4paI4oCB4paI4paI4oCBIOKAgeKAgeKAgSDilojilojigIHilojilojigIHilojilojilojilojilojilojilojigIF0aHJlYWRpbmcgYWRkZWQgYnkgdGhlcmVhbHJlZWQgb24gZ2l0aHViICAoOCB0aHJlYWRzKQ0KIiIiICsgRm9yZS5MSUdIVENZQU5fRVgpDQogICAgcHJpbnQoYmFubmVyKQ0KDQpkZWYgbWFpbigpOg0KICAgIGluaXQoKQ0KICAgIGNsZWFyX2NvbnNvbGUoKQ0KICAgIHByaW50X2Jhbm5lcigpDQogICAgcHJpbnQoZiJ7Rm9yZS5NQUdFTlRBfVskXXtTdHlsZS5SRVNFVF9BTEx9ICAgIERldjp7U3R5bGUuUkVTRVRfQUxMfSB7Rm9yZS5NQUdFTlRBfUhlcm1pcyBhbmQgdGhlcmVhbHJlZWR7Rm9yZS5XSElURX0gPDMiKQ0KICAgIHRpbWUuc2xlZXAoMykNCiAgICBjbGVhcl9jb25zb2xlKCkNCiAgICBwcm94aWVzID0gW10NCg0KICAgICMgSWYgdXNpbmcgcHJveGllcywgcmVhZCBwcm94aWVzIGZyb20gZmlsZQ0KICAgIGlmIHVzZV9wcm94aWVzOg0KICAgICAgICBwcm94eV9maWxlX3BhdGggPSAncHJveGllcy50eHQnDQogICAgICAgIHByb3hpZXMgPSByZWFkX3Byb3hpZXNfZnJvbV9maWxlKHByb3h5X2ZpbGVfcGF0aCkNCg0KICAgICAgICAjIENoZWNrIGlmIHByb3hpZXMgYXJlIHdvcmtpbmcNCiAgICAgICAgd29ya2luZ19wcm94aWVzID0gW3Byb3h5IGZvciBwcm94eSBpbiBwcm94aWVzIGlmIGNoZWNrX3Byb3h5KHByb3h5KV0NCg0KICAgICAgICBpZiBub3Qgd29ya2luZ19wcm94aWVzOg0KICAgICAgICAgICAgcHJpbnQoZiJ7Rm9yZS5SRUR9Tm8gd29ya2luZyBwcm94aWVzIGZvdW5kLiBFeGl0aW5nLntGb3JlLlJFU0VUfSIpDQogICAgICAgICAgICByZXR1cm4NCiAgICAgICAgZWxzZToNCiAgICAgICAgICAgIHByaW50KGYie0ZvcmUuR1JFRU59WytdIFByb3hpZXMgYXJlIHdvcmtpbmcue0ZvcmUuUkVTRVR9IikNCiAgICAgICAgICAgIHByb3hpZXMgPSB3b3JraW5nX3Byb3hpZXMNCg0KICAgICMgSW5wdXQgdmFsaWRhdGlvbg0Kd2hpbGUgVHJ1ZToNCiAgICB0cnk6DQogICAgICAgIG51bV90b2tlbnNfdG9fZ2VuZXJhdGUgPSBpbnQoaW5wdXQoZiJ7Rm9yZS5NQUdFTlRBfVskXXtTdHlsZS5SRVNFVF9BTEx9ICAgIEhPVyBNQU5ZIFRPS0VOUyAgOiB7Rm9yZS5NQUdFTlRBfSIpKQ0KICAgICAgICB1c2VyX2lkID0gaW5wdXQoDQogICAgICAgICAgICBmIntGb3JlLk1BR0VOVEF9WyRde1N0eWxlLlJFU0VUX0FMTH0gICAgVVNFUiBJRCAgOiB7Rm9yZS5NQUdFTlRBfSIpDQogICAgICAgIHRocmVhZHNzcyA9IGludChpbnB1dChmIntGb3JlLk1BR0VOVEF9WyRde1N0eWxlLlJFU0VUX0FMTH0gICAgSE9XIE1BTlkgVEhSRUFEUyAgOiB7Rm9yZS5NQUdFTlRBfSIpKQ0KICAgICAgICB1c2VfcHJveGllcyA9IGlucHV0KGYie0ZvcmUuTUFHRU5UQX1bJF17U3R5bGUuUkVTRVRfQUxMfSAgICBVc2UgUHJveGllcz8gKHkvbikgIDoge0ZvcmUuTUFHRU5UQX0iKS5sb3dlcigpID09ICd5Jw0KICAgICAgICBwcm94aWVzID0gW10NCiAgICAgICAgaWYgbm90IHVzZXJfaWQuaXNkaWdpdCgpOg0KICAgICAgICAgICAgcmFpc2UgVmFsdWVFcnJvcg0KICAgICAgICBicmVhaw0KDQogICAgZXhjZXB0IFZhbHVlRXJyb3I6DQogICAgICAgICAgICBwcmludChmIntGb3JlLlJFRH1QbGVhc2UgZW50ZXIgYSB2YWxpZCBudW1iZXIue0ZvcmUuUkVTRVR9IikNCg0KICAgICMgSWYgdXNpbmcgcHJveGllcywgcmVhZCBwcm94aWVzIGZyb20gZmlsZQ0KICAgIGlmIHVzZV9wcm94aWVzOg0KICAgICAgICBwcm94eV9maWxlX3BhdGggPSAncHJveGllcy50eHQnDQogICAgICAgIHByb3hpZXMgPSByZWFkX3Byb3hpZXNfZnJvbV9maWxlKHByb3h5X2ZpbGVfcGF0aCkNCg0KICAgICAgICAjIENoZWNrIGlmIHByb3hpZXMgYXJlIHdvcmtpbmcNCiAgICAgICAgd29ya2luZ19wcm94aWVzID0gW3Byb3h5IGZvciBwcm94eSBpbiBwcm94aWVzIGlmIGNoZWNrX3Byb3h5KHByb3h5KV0NCg0KICAgICAgICBpZiBub3Qgd29ya2luZ19wcm94aWVzOg0KICAgICAgICAgICAgcHJpbnQoZiJ7Rm9yZS5SRUR9Tm8gd29ya2luZyBwcm94aWVzIGZvdW5kLiBFeGl0aW5nLntGb3JlLlJFU0VUfSIpDQogICAgICAgIGVsc2U6DQogICAgICAgICAgICBwcmludChmIntGb3JlLkdSRUVOfVsrXSBQcm94aWVzIGFyZSB3b3JraW5nLntGb3JlLlJFU0VUfSIpDQogICAgICAgICAgICBwcm94aWVzID0gd29ya2luZ19wcm94aWVzDQogICAgY2xlYXJfY29uc29sZSgpDQpkZWYgcGFydCgpOg0KICAgIGZvciBfIGluIHJhbmdlKG51bV90b2tlbnNfdG9fZ2VuZXJhdGUpOg0KICAgICAgICB0b2tlbiA9IGdldF90b2tlbih1c2VyX2lkKQ0KICAgICAgICBwcm94eSA9IHJhbmRvbS5jaG9pY2UocHJveGllcykgaWYgdXNlX3Byb3hpZXMgZWxzZSBOb25lDQogICAgICAgIGNoZWNrX3Rva2VuX3ZhbGlkaXR5KHRva2VuLCBwcm94eSkNCg0KICAgIHRpbWUuc2xlZXAoMS41KQ0KICAgIHByaW50X2Jhbm5lcigpDQogICAgcHJpbnQoZiJ7Rm9yZS5DWUFOfVskXXtTdHlsZS5SRVNFVF9BTEx9ICAgIEZpbmlzaGVkIGdlbmVyYXRpbmdcbntGb3JlLkNZQU59WyRde1N0eWxlLlJFU0VUX0FMTH0gICAgUHJlc3MgRW50ZXIgdG8gZXhpdC4uIikNCiAgICBpbnB1dCgpDQoNCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6DQogICAgdGhyZWFkcyA9IFtdICAjIENyZWF0ZSBhIGxpc3QgdG8gaG9sZCBhbGwgdGhyZWFkcw0KICAgIGZvciBfIGluIHJhbmdlKHRocmVhZHNzcyk6ICAjIFJlcGxhY2UgMTAgd2l0aCB0aGUgYWN0dWFsIG51bWJlciBvZiB0aHJlYWRzIHlvdSB3YW50DQogICAgICAgIHRocmVhZCA9IHRocmVhZGluZy5UaHJlYWQodGFyZ2V0PXBhcnQsIGFyZ3M9KCkpICAjIENyZWF0ZSBhIG5ldyB0aHJlYWQNCiAgICAgICAgdGhyZWFkcy5hcHBlbmQodGhyZWFkKSAgIyBBZGQgdGhlIG5ldyB0aHJlYWQgdG8gdGhlIGxpc3QNCiAgICAgICAgdGhyZWFkLnN0YXJ0KCkgICMgU3RhcnQgdGhlIG5ldyB0aHJlYWQNCg0KICAgIGZvciB0aHJlYWQgaW4gdGhyZWFkczoNCiAgICAgICAgdGhyZWFkLmpvaW4oKSAgIyBXYWl0IGZvciBhbGwgdGhyZWFkcyB0byBjb21wbGV0ZQ0KIA0K

**Comment by xHERMIS** [comment]
You didn't have to do
