### ISSUE TITLE
Statistically unlikely for it to work

### ISSUE THREAD

**Issue by stefnotch** [xHERMIS/ID-to-TOKEN#6]
This popped up in my GitHub recommendations, so I checked it out. 

So a token is being generated here
https://github.com/xHERMIS/ID-to-TOKEN/blob/115bed8e94ee3859b0138fa750f82f1a7dbf0bb5/ID%20to%20TOKEN.py#L31

And each character of a token can be either one of the 26 letters, or one of the 10 digits.
And we're generating 6+38 such characters to form one token.

This means, we have (26+10)^(6+38) different potential tokens for a given user. And only one of them is correct. If we generate and check a downright ridiculous 1 billion tokens per millisecond, then it still takes a while to crunch through all of the tokens.

https://www.wolframalpha.com/input?i=%2826%2B10%29%5E%286%2B38%29%2F%2810%5E9%29+milliseconds

But wait, on average we only need to crunch through half of them before getting a hit! Well, half of that is still ≈ 350000000000000000000000000000000000000 × age of the universe 💀

**Comment by jojo989** [comment]
this shit is just bruteforcing a token

**Comment by xHERMIS** [comment]
I wrote this code in my free time (I don't know what I do)

**Comment by stefnotch** [comment]
I figured as much :)

Personally, I saw a chance to teach a little bit and give you the skills required to figure out when a brute forcer could work, and when it's hopeless. (Maths can be surprisingly useful.)

Do feel free to add a disclaimer to the Readme that says something along the lines of "❗ This isn't serious. If you do run the code, you better roll a Nat 20 to have any hope of it finishing before the universe expires."

**Comment by populated** [comment]
> I wrote this code in my free time (I don't know what I do)



> This popped up in my GitHub recommendations, so I checked it out.
> 
> So a token is being generated here
> 
> https://github.com/xHERMIS/ID-to-TOKEN/blob/115bed8e94ee3859b0138fa750f82f1a7dbf0bb5/ID%20to%20TOKEN.py#L31
> 
> And each character of a token can be either one of the 26 letters, or one of the 10 digits. And we're generating 6+38 such characters to form one token.
> 
> This means, we have (26+10)^(6+38) different potential tokens for a given user. And only one of them is correct. If we generate and check a downright ridiculous 1 billion tokens per millisecond, then it still takes a while to crunch through all of the tokens.
> 
> https://www.wolframalpha.com/input?i=%2826%2B10%29%5E%286%2B38%29%2F%2810%5E9%29+milliseconds
> 
> But wait, on average we only need to crunch through half of them before getting a hit! Well, half of that is still ≈ 350000000000000000000000000000000000000 × age of the universe 💀

These calculations are correct, but honestly, they can become invalid. The second part of the token is publicly available; it's the timestamp of the account creation, which you can obtain by reversing the UID. This means you'd only have to brute-force the third part, which is the cryptographic component. Now, the search space is still pretty large, around `(26+10)^38`, but compared to the old pool, which is `36^6` times larger. I'd say it's a decrease, still impossible though. :]

---

![structure](https://github.com/xHERMIS/ID-to-TOKEN/assets/149972831/6aef91bb-4370-4434-b375-5fcd5704da6a)
