### ISSUE TITLE
Wow.

### ISSUE THREAD

**Issue by alluding** [xHERMIS/ID-to-TOKEN#8]
Just, absolutely wow. Where do I begin with this horrid code? First of all, as @stefnotch stated, the statistics and logicality of this code are non-existent. It's just not possible to brute-force a token. Okay, so he already did some of the math about a token's parts, but I'd rather go a bit more in-depth.

So, a Discord token has three parts. If you decode the first part of the token, which is base64 to a string, it returns the user ID. You already know this since that is what the script is doing in just reverse order. Anyway, onto the next part. The second part of the token, if you decode it base64 as well, you get a timestamp. Then you use the epoch for tokens, which is `1293840000`, and with that result, you decode the Unix timestamp, and then you can get the timestamp at which it was created.

Now, the third part. Let's just say it's impossible since that's the HMAC, a cryptographic component. It's simply impossible to "brute-force" a token. The most you can do is use the fact that the first two parts of the token are technically "public" and reverse the process of decoding to encode them. So, you can use the user's timestamp, which is publicly available, and the user ID as well, to retrieve those. However, hoping to somehow magically retrieve the third part, the cryptographic one, is doubtful. Tokens are invalidated upon logout/login, and a new one is generated each time, so there's no static token; they're all dynamic.

----

![structure](https://github.com/xHERMIS/ID-to-TOKEN/assets/149972831/1dae675f-7a2d-4f7d-bc72-cd525b51a207)

**Comment by xHERMIS** [comment]
nobody cares

**Comment by alluding** [comment]
> nobody cares

One word to describe you and your attitude: `skid`. 🤣
